version: '3.4'

services:
  postgres:
    image: postgres:14.2-alpine3.15
    container_name: 'postgre'
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - checkout

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data://root/.pgadmin
    networks:
      - checkout

  redis:
    image: redis:6.2
    container_name: 'redis'
    ports:
      - 6002:6379
    networks:
      - checkout

  redis_2:
    image: redis:6.2
    container_name: 'redis_2'
    ports:
      - 6003:6379
    networks:
      - checkout

  redis_3:
    image: redis:6.2
    container_name: 'redis_3'
    ports:
      - 6004:6379
    networks:
      - checkout

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5003:5672
      - 5004:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - checkout

  elasticsearch:
    container_name: dt-els
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - checkout

  kibana:
    container_name: dt-kibana
    image: docker.elastic.co/kibana/kibana:7.16.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - checkout

networks:
  checkout:
    driver: bridge

volumes:
  db_volume:
  rabbitmq_data:
  rabbitmq_log:
  pgadmin_data:
  elasticsearch-data: