apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: identityserver
  name: identityserver
spec:
  replicas: 10
  selector:
    matchLabels:
      app: identityserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: identityserver
    spec:
      containers:
      - image: kursatarslan/identityserver:latest
        name: identityserver
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 5009 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: identityserver
  labels:
    run: identityserver
spec:
  ports:
  - port: 5009
    protocol: TCP
  selector:
    app: identityserver
  type: NodePort