apiVersion: v1
kind: Pod
metadata:
  name: identityserver
spec:
  containers:
    - image: 192.168.49.2:5000/identityserver:latest
      name: identityserver
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 5009