apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: merchant
  name: merchant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merchant
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: merchant
    spec:
      containers:
      - image: kursatarslan/merchant:1.8
        name: merchant
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 5008
        env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Staging"
          - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
            value: "true"
          - name: ReactSettings__ApiUrl
            value: "merchantcom"
          - name: ReactSettings__ApiGatewayUrl
            value: "https://192.168.49.2:30886" 
status: {}