apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: kursatarslan/merchant:latest
      name: webapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 5008